export {
  createQuickPhrase,
  deleteQuickPhrase,
  getAnalyticsSettings,
  getEmailSettings,
  getPublicSettings,
  getWebhookSettings,
  listQuickPhrases,
  reorderQuickPhrases,
  saveAnalyticsSettings,
  saveEmailSettings,
  saveWebhookSettings,
  sendTestEmail,
  updateQuickPhrase,
} from './api/settingsApi';
export type {
  AnalyticsSettings,
  AnalyticsSettingsPayload,
  EmailSettings,
  EmailSettingsPayload,
  EmailSources,
  PublicSettings,
  QuickPhrase,
  QuickPhrasePayload,
  TestEmailResult,
  WebhookSettings,
} from './api/settingsApi';
