/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * {"username", "password", "remember_me"?}: the session starts and the answer is who signed in. 401
         *     invalid_credentials for a wrong username or password.
         */
        post: operations["post_api_auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ends the session: 204. */
        post: operations["post_api_auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who is signed in. 401 when nobody is. */
        get: operations["get_api_auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every user, by name. */
        get: operations["get_api_users_list"];
        put?: never;
        /** UserInput: creates a user. The password is required. 422 when invalid. */
        post: operations["post_api_users_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One user. 404 user_not_found. */
        get: operations["get_api_users_show"];
        /** UserInput: edits a user; a blank password keeps the current one. 404 user_not_found, 422 when invalid. */
        put: operations["put_api_users_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/by-code/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A product by its code (the barcode reader). 404 product_not_found. */
        get: operations["get_api_products_by_code"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A product by uuid. 404 product_not_found. */
        get: operations["get_api_products_show"];
        /** ProductInput: edits a product. 404 product_not_found. */
        put: operations["put_api_products_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ProductInput: creates a product (no stock until some is uploaded, scanned or moved). */
        post: operations["post_api_products_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * multipart: `file` (xls/xlsx, the template's columns) and `warehouse_id`: the products are created or updated and
         *     their quantities added to the warehouse's stock. 404 warehouse_not_found; 415 unsupported_media; 422
         *     invalid_spreadsheet.
         */
        post: operations["post_api_products_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/template.xls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The stock spreadsheet (an xls attachment): `all=1` for every product, or `uuid[]=…` for the selected ones; with
         *     neither, the header alone.
         */
        get: operations["get_api_products_template"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/warehouses/{id}/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The warehouse's stock rows with `status` (1 in stock, default; 0 incoming), by product. 404 warehouse_not_found. */
        get: operations["get_api_stock_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/warehouses/{from}/moves/{to}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * StockLinesInput: moves quantities to another warehouse (they arrive as incoming). 204; 409 same_warehouse;
         *     404 product_not_found, stock_not_found, warehouse_not_found; 422 insufficient_stock (detail: code, available).
         */
        post: operations["post_api_stock_move"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/warehouses/{id}/stock/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** StockLinesInput (by code): the barcode reader adds stock; an unknown code is skipped. 204. */
        post: operations["post_api_stock_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/warehouses/{id}/stock/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * StockLinesInput (by code): the barcode reader removes stock; an unknown code is skipped. 204; 404 stock_not_found;
         *     422 insufficient_stock (detail: code, available).
         */
        post: operations["post_api_stock_remove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/warehouses/{id}/incoming/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approves every incoming row of the warehouse. 404 warehouse_not_found. */
        post: operations["post_api_stock_approve_incoming"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/warehouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every warehouse, by id (as /admin/warehouse/all: any signed-in user). */
        get: operations["get_api_warehouses_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/warehouses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** WarehouseInput: renames a warehouse (as the legacy edit: any signed-in user). 404 warehouse_not_found. */
        put: operations["put_api_warehouses_rename"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `page` (1…), `per_page` (100 by default and at most, as the legacy list). Customers by id. */
        get: operations["get_api_customers_page"];
        put?: never;
        /**
         * CustomerInput: creates a customer, or, as the legacy form did, updates the one the id, else the email, else the
         *     phone names. 422 without a first name or an email.
         */
        post: operations["post_api_customers_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every customer, for the order and invoice pickers (those without an address too). */
        get: operations["get_api_customers_all"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One customer. 404 customer_not_found. */
        get: operations["get_api_customers_show"];
        /** CustomerInput: edits a customer and replaces their addresses. 404 customer_not_found. */
        put: operations["put_api_customers_update"];
        post?: never;
        /** Deletes a customer (soft delete, as before), and with them their orders. 204; 404 customer_not_found. */
        delete: operations["delete_api_customers_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every country with its states and their cities, all of them, by id. */
        get: operations["get_api_locations_tree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `warehouse_id`: that warehouse's orders, newest first (the list filters and pages them in the browser). */
        get: operations["get_api_orders_list"];
        put?: never;
        /**
         * OrderInput: places an order (the customer is found by id, email or phone and updated, or created); the printer
         *     gets its email. 422 order_without_products; 404 product_not_found, warehouse_not_found.
         */
        post: operations["post_api_orders_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One order with its customer (and addresses), comments and products. 404 order_not_found. */
        get: operations["get_api_orders_show"];
        /** OrderInput: edits an order (its comments are not touched: PUT …/comments). 404 order_not_found. */
        put: operations["put_api_orders_update"];
        post?: never;
        /** Deletes an order: its product lines and comments, then the order (soft delete: it is not found any more). 204. */
        delete: operations["delete_api_orders_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** OrderStatusInput: moves the order to another status (a status history row; stock is not touched). */
        post: operations["post_api_orders_status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * OrderCommentsInput: the order's comments as they should be: no id adds one (signed by you), an id edits it, a
         *     comment left out leaves the order. As before: any signed-in user.
         */
        put: operations["put_api_orders_comments"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pulls new orders from the WooCommerce shops (item 13). 501 order_sync_unavailable until then; 502 order_sync_failed. (item 13). */
        post: operations["post_api_orders_sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The order as a PDF (the printer's). */
        get: operations["get_api_orders_pdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/remaining-pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What is left to ship, as a PDF. */
        get: operations["get_api_orders_remaining_pdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/xls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The order's products as a spreadsheet (date, product code, quantity). As before: any signed-in user, and the
         *     file is named after product.xls.filename and the order code.
         */
        get: operations["get_api_orders_xls"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/partials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What was shipped, what is left, and the warehouse's stock of the order's products. As before: any signed-in
         *     user.
         */
        get: operations["get_api_orders_partials"];
        put?: never;
        /**
         * PartialInput: ships these products now. Exactly the whole order, in stock: the order is sent (status 5);
         *     otherwise a partial shipment (status 4). Either way the products leave the order's warehouse. 409
         *     partial_exceeds_order (more than what is left, or the order is already sent); 422 insufficient_stock.
         */
        post: operations["post_api_orders_partials_record"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every invoice, newest first. (item 5). */
        get: operations["get_api_invoices_list"];
        put?: never;
        /** InvoiceInput: creates an invoice. 409 invoice_code_taken. (item 5). */
        post: operations["post_api_invoices_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/next-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The code the next invoice is offered. (item 5). */
        get: operations["get_api_invoices_next_code"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One invoice. 404 invoice_not_found. (item 5). */
        get: operations["get_api_invoices_show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The invoice as a PDF. (item 5). */
        get: operations["get_api_invoices_pdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SessionOutput: {
            id: number;
            username: string;
            name?: string | null;
            email?: string | null;
            roles: string[];
        };
        UserOutput: {
            id: number;
            name: string;
            username: string;
            email?: string | null;
            /** The roles assigned (not the ones reached through the hierarchy) */
            roles: string[];
            enabled: boolean;
        };
        ProductStockOutput: {
            warehouse_id: number;
            quantity: number;
            /** 1: in stock; 0: incoming */
            status: number;
        };
        ProductOutput: {
            id: number;
            uuid: string;
            code: string;
            title: string;
            detail?: string | null;
            /** 1: active; 0: inactive */
            status: number;
            /** Format: float */
            price?: number | null;
            stock: components["schemas"]["ProductStockOutput"][];
        };
        UploadResultOutput: {
            /** Rows stored (created or added to) */
            stored: number;
        };
        WarehouseRefOutput: {
            id: number;
            name: string;
        };
        StockOutput: {
            /** The stock row */
            id: number;
            /** 1: in stock; 0: incoming, waiting for approval */
            status: number;
            quantity: number;
            product_id: number;
            /** The product's */
            uuid: string;
            code: string;
            title: string;
            detail?: string | null;
            /** Format: float */
            price?: number | null;
            warehouse: components["schemas"]["WarehouseRefOutput"];
        };
        ApprovedOutput: {
            approved: number;
        };
        WarehouseOutput: {
            id: number;
            name: string;
            /** The X-WC-Webhook-Source values that send orders here */
            urls: string[];
        };
        CountryRefOutput: {
            id: number;
            name: string;
            code?: string | null;
        };
        StateRefOutput: {
            id: number;
            name: string;
            code?: string | null;
            country: components["schemas"]["CountryRefOutput"];
        };
        CityRefOutput: {
            id: number;
            name: string;
            state: components["schemas"]["StateRefOutput"];
        };
        AddressOutput: {
            id: number;
            address?: string | null;
            zip_code?: string | null;
            /** 1: billing; 2: shipping (as the WooCommerce webhook stores them) */
            address_type?: number | null;
            city?: components["schemas"]["CityRefOutput"] | null;
        };
        CustomerOutput: {
            id: number;
            first_name?: string | null;
            last_name?: string | null;
            email?: string | null;
            phone?: string | null;
            addresses: components["schemas"]["AddressOutput"][];
        };
        CityOutput: {
            id: number;
            name: string;
        };
        StateOutput: {
            id: number;
            name: string;
            code?: string | null;
            cities: components["schemas"]["CityOutput"][];
        };
        CountryOutput: {
            id: number;
            name: string;
            code?: string | null;
            states: components["schemas"]["StateOutput"][];
        };
        CustomerRefOutput: {
            id: number;
            first_name?: string | null;
            last_name?: string | null;
            email?: string | null;
            phone?: string | null;
        };
        OrderOutput: {
            id: number;
            code?: string | null;
            /** 1 created, 2 processed, 3 completed, 4 partial, 5 sent, 6 delivered */
            status: number;
            /** 1 web (WooCommerce), 2 phone */
            source: number;
            /** 1 credit card, 2 PayPal */
            payment_method?: number | null;
            comment?: string | null;
            /** ISO 8601 */
            created_at?: string | null;
            warehouse?: components["schemas"]["WarehouseRefOutput"] | null;
            customer?: components["schemas"]["CustomerRefOutput"] | null;
            comments_count: number;
        };
        OrderCommentOutput: {
            id: number;
            content?: string | null;
        };
        OrderLineProductOutput: {
            code: string;
            title: string;
            detail?: string | null;
        };
        OrderLineOutput: {
            /** The product's */
            uuid: string;
            quantity: number;
            product: components["schemas"]["OrderLineProductOutput"];
        };
        OrderDetailOutput: {
            id: number;
            code?: string | null;
            status: number;
            source: number;
            payment_method?: number | null;
            comment?: string | null;
            /** ISO 8601 */
            created_at?: string | null;
            warehouse?: components["schemas"]["WarehouseRefOutput"] | null;
            customer?: components["schemas"]["CustomerOutput"] | null;
            comments: components["schemas"]["OrderCommentOutput"][];
            products: components["schemas"]["OrderLineOutput"][];
        };
        SyncResultOutput: {
            imported: number;
            /** Already imported, or from a warehouse without credentials */
            skipped: number;
        };
        PartialLineProductOutput: {
            code: string;
        };
        PartialLineOutput: {
            uuid: string;
            quantity: number;
            product: components["schemas"]["PartialLineProductOutput"];
        };
        PendingLineOutput: {
            uuid: string;
            quantity: number;
        };
        OrderPartialsOutput: {
            order_id: number;
            status: number;
            products_aggregate: components["schemas"]["PartialLineOutput"][];
            pending: components["schemas"]["PendingLineOutput"][];
            inventory: components["schemas"]["StockOutput"][];
        };
        InvoiceProductOutput: {
            id: number;
            code: string;
        };
        InvoiceItemOutput: {
            id: number;
            description?: string | null;
            quantity: number;
            unit_price: string;
            discount?: string | null;
            total: string;
            product?: components["schemas"]["InvoiceProductOutput"] | null;
        };
        InvoiceOutput: {
            id: number;
            code?: string | null;
            status?: number | null;
            customer?: components["schemas"]["CustomerRefOutput"] | null;
            customer_nit?: string | null;
            customer_address?: string | null;
            comment?: string | null;
            payment_method?: string | null;
            items: components["schemas"]["InvoiceItemOutput"][];
            /** total minus tax_amount */
            subtotal?: string | null;
            tax_rate?: string | null;
            tax_amount?: string | null;
            total?: string | null;
            /** ISO 8601 */
            created_at?: string | null;
        };
        NextInvoiceCodeOutput: {
            code: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_api_auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOutput"];
                };
            };
        };
    };
    post_api_auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOutput"];
                };
            };
        };
    };
    get_api_users_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOutput"][];
                };
            };
        };
    };
    post_api_users_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOutput"];
                };
            };
        };
    };
    get_api_users_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOutput"];
                };
            };
        };
    };
    put_api_users_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOutput"];
                };
            };
        };
    };
    get_api_products_by_code: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOutput"];
                };
            };
        };
    };
    get_api_products_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOutput"];
                };
            };
        };
    };
    put_api_products_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOutput"];
                };
            };
        };
    };
    post_api_products_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOutput"];
                };
            };
        };
    };
    post_api_products_upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResultOutput"];
                };
            };
        };
    };
    get_api_products_template: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_stock_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockOutput"][];
                };
            };
        };
    };
    post_api_stock_move: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                from: string;
                to: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_api_stock_add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_api_stock_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_api_stock_approve_incoming: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovedOutput"];
                };
            };
        };
    };
    get_api_warehouses_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarehouseOutput"][];
                };
            };
        };
    };
    put_api_warehouses_rename: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarehouseOutput"];
                };
            };
        };
    };
    get_api_customers_page: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["CustomerOutput"][];
                        total: number;
                        page: number;
                        per_page: number;
                    };
                };
            };
        };
    };
    post_api_customers_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOutput"];
                };
            };
        };
    };
    get_api_customers_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOutput"][];
                };
            };
        };
    };
    get_api_customers_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOutput"];
                };
            };
        };
    };
    put_api_customers_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOutput"];
                };
            };
        };
    };
    delete_api_customers_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_locations_tree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryOutput"][];
                };
            };
        };
    };
    get_api_orders_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOutput"][];
                };
            };
        };
    };
    post_api_orders_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailOutput"];
                };
            };
        };
    };
    get_api_orders_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailOutput"];
                };
            };
        };
    };
    put_api_orders_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailOutput"];
                };
            };
        };
    };
    delete_api_orders_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_api_orders_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailOutput"];
                };
            };
        };
    };
    put_api_orders_comments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        comments: components["schemas"]["OrderCommentOutput"][];
                    };
                };
            };
        };
    };
    post_api_orders_sync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResultOutput"];
                };
            };
        };
    };
    get_api_orders_pdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_orders_remaining_pdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_orders_xls: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_orders_partials: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPartialsOutput"];
                };
            };
        };
    };
    post_api_orders_partials_record: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPartialsOutput"];
                };
            };
        };
    };
    get_api_invoices_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceOutput"][];
                };
            };
        };
    };
    post_api_invoices_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceOutput"];
                };
            };
        };
    };
    get_api_invoices_next_code: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextInvoiceCodeOutput"];
                };
            };
        };
    };
    get_api_invoices_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceOutput"];
                };
            };
        };
    };
    get_api_invoices_pdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
