/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/settings/quick-phrases/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * QuickPhraseOrderInput: the phrases' new order (these ids first, the others after them) → every phrase. 404
         *     quick_phrase_not_found for an id that is not a phrase.
         */
        put: operations["put_api_quick_phrases_order"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * {"username", "password", "remember_me"?}: the session starts and the answer is who signed in. 401
         *     invalid_credentials for a wrong username or password.
         */
        post: operations["post_api_auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ends the session: 204. */
        post: operations["post_api_auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who is signed in. 401 when nobody is. */
        get: operations["get_api_auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A page of users, by name: the list contract (q over name, username and email; filters name, username, email,
         *     roles[] — the nine assignable, any of them —, enabled[] yes/no; sorts name, username, email; facets of roles and
         *     enabled).
         */
        get: operations["get_api_users_list"];
        put?: never;
        /** UserInput: creates a user. The password is required. 422 when invalid. */
        post: operations["post_api_users_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One user. 404 user_not_found. */
        get: operations["get_api_users_show"];
        /** UserInput: edits a user; a blank password keeps the current one. 404 user_not_found, 422 when invalid. */
        put: operations["put_api_users_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/by-code/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A product by its code (the barcode reader). 404 product_not_found. */
        get: operations["get_api_products_by_code"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A product by uuid. 404 product_not_found. */
        get: operations["get_api_products_show"];
        /** ProductInput: edits a product. 404 product_not_found. */
        put: operations["put_api_products_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ProductInput: creates a product (no stock until some is uploaded, scanned or moved). */
        post: operations["post_api_products_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * multipart: `file` (xls/xlsx, the template's columns) and `warehouse_id`: the products are created or updated and
         *     their quantities added to the warehouse's stock. 404 warehouse_not_found; 415 unsupported_media; 422
         *     invalid_spreadsheet.
         */
        post: operations["post_api_products_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/template.xls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The stock spreadsheet (an xls attachment): `all=1` for every product, or `uuid[]=…` for the selected ones; with
         *     neither, the header alone.
         */
        get: operations["get_api_products_template"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/warehouses/{id}/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A page of the warehouse's stock rows with `status` (1 in stock, default; 0 incoming): the list contract (q over
         *     code, title and detail; filters code, title, detail, quantity, price, in_stock; sorts code, title, quantity,
         *     price; facet of in_stock; `per_page=0` every row, for the pickers) and `totals` (units, value) over every row
         *     the filters keep, whatever the page. 404 warehouse_not_found.
         */
        get: operations["get_api_stock_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/warehouses/{from}/moves/{to}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * StockLinesInput: moves quantities to another warehouse (they arrive as incoming). 204; 409 same_warehouse;
         *     404 product_not_found, stock_not_found, warehouse_not_found; 422 insufficient_stock (detail: code, available).
         */
        post: operations["post_api_stock_move"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/warehouses/{id}/stock/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** StockLinesInput (by code): the barcode reader adds stock; an unknown code is skipped. 204. */
        post: operations["post_api_stock_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/warehouses/{id}/stock/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * StockLinesInput (by code): the barcode reader removes stock; an unknown code is skipped. 204; 404 stock_not_found;
         *     422 insufficient_stock (detail: code, available).
         */
        post: operations["post_api_stock_remove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/warehouses/{id}/incoming/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approves every incoming row of the warehouse. 404 warehouse_not_found. */
        post: operations["post_api_stock_approve_incoming"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/warehouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every warehouse, by id (as /admin/warehouse/all: any signed-in user). */
        get: operations["get_api_warehouses_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/warehouses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** WarehouseInput: renames a warehouse (as the legacy edit: any signed-in user). 404 warehouse_not_found. */
        put: operations["put_api_warehouses_rename"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A page of customers, newest first: the list contract (q over first/last name, email, phone and city; filters
         *     name, email, phone, city (the first address's), country[] (country ids, any address); sorts name, email, city;
         *     facet of country).
         */
        get: operations["get_api_customers_page"];
        put?: never;
        /**
         * CustomerInput: creates a customer, or, as the legacy form did, updates the one the id, else the email, else the
         *     phone names. 422 without a first name or an email.
         */
        post: operations["post_api_customers_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every customer, for the order and invoice pickers (those without an address too). Whoever the legacy order and
         *     invoice forms embedded the list for reads it: ROLE_MANAGE_CUSTOMERS, ROLE_CAN_CREATE_ORDERS,
         *     ROLE_CAN_UPDATE_ORDERS or ROLE_CAN_CREATE_INVOICES.
         */
        get: operations["get_api_customers_all"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One customer. 404 customer_not_found. */
        get: operations["get_api_customers_show"];
        /** CustomerInput: edits a customer and replaces their addresses. 404 customer_not_found. */
        put: operations["put_api_customers_update"];
        post?: never;
        /** Deletes a customer (soft delete, as before), and with them their orders. 204; 404 customer_not_found. */
        delete: operations["delete_api_customers_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every country with its states and their cities, all of them, by id. */
        get: operations["get_api_locations_tree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The order's comments, oldest first (on the same date, in the order they were written); a legacy comment
         *     without a date carries the order's (`approximate`); shop notes (`origin` shop) name their shop and no author.
         * @description 404 order_not_found.
         */
        get: operations["get_api_order_comments"];
        /**
         * OrderCommentsInput: the order's comments as they should be: no id adds one (signed by you), an id edits it, a
         *     comment left out leaves the order. As before: any signed-in user.
         */
        put: operations["put_api_orders_comments"];
        /**
         * AddOrderCommentInput → 201 the comment (signed by you, dated now; `origin` phrase with an active `phrase_id`).
         * @description 422 shop_note_unavailable when `send_to_shop` cannot be done (the order is not from a connection, or the
         *     connection is inactive or its order_note capability is off): nothing is written. 404 order_not_found,
         *     quick_phrase_not_found.
         */
        post: operations["post_api_order_comments_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/comments/{commentId}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pins the comment (the order's only pinned one: the previous one is unpinned). 404 order_not_found,
         *     comment_not_found (also for another order's comment).
         */
        post: operations["post_api_order_comments_pin"];
        /** Unpins it (a comment that is not pinned is left as it is). 404 order_not_found, comment_not_found. */
        delete: operations["delete_api_order_comments_unpin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `warehouse_id` (required): a page of that warehouse's orders, newest first — the list contract (q over code,
         *     customer name and email; filters code, customer (name or email), status[] 1–6, source[] phone|web|shop:<id>
         *     (web: a web order no connection brought), created_at, pinned[] 1; sorts code, customer, status, created_at;
         *     facets of status, source and pinned).
         */
        get: operations["get_api_orders_list"];
        put?: never;
        /**
         * OrderInput: places an order (the customer is found by id, email or phone and updated, or created); the printer
         *     gets its email. 422 order_without_products; 404 product_not_found, warehouse_not_found.
         */
        post: operations["post_api_orders_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One order with its customer (and addresses), comments and products. 404 order_not_found. */
        get: operations["get_api_orders_show"];
        /** OrderInput: edits an order (its comments are not touched: PUT …/comments). 404 order_not_found. */
        put: operations["put_api_orders_update"];
        post?: never;
        /** Deletes an order: its product lines and comments, then the order (soft delete: it is not found any more). 204. */
        delete: operations["delete_api_orders_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** OrderStatusInput: moves the order to another status (a status history row; stock is not touched). */
        post: operations["post_api_orders_status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * "Check now": the catch-up pull of every active shop connection, due or not, each in its own transaction
         *     (docs/pdr/prd-shops-settings.md, Decisions 11). 202 with what each connection brought in — `imported` placed,
         *     `skipped` already in the app or kept in the failed-deliveries inbox — and `error` for a shop that could not be
         *     read (recorded in its health; the others go on). 502 order_sync_failed only when every connection failed.
         * @description Without an active connection nothing is pulled.
         */
        post: operations["post_api_orders_sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The order as a PDF (the printer's). */
        get: operations["get_api_orders_pdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/remaining-pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What is left to ship, as a PDF. */
        get: operations["get_api_orders_remaining_pdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/xls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The order's products as a spreadsheet (date, product code, quantity). As before: any signed-in user, and the
         *     file is named after product.xls.filename and the order code.
         */
        get: operations["get_api_orders_xls"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/partials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The order's code and lines, what was shipped, what is left, and the warehouse's stock of the order's products:
         *     all the getting-ready screen shows. As before: any signed-in user.
         */
        get: operations["get_api_orders_partials"];
        put?: never;
        /**
         * PartialInput: ships these products now. Exactly the whole order, in stock: the order is sent (status 5);
         *     otherwise a partial shipment (status 4). Either way the products leave the order's warehouse. 409
         *     partial_exceeds_order (more than what is left, or the order is already sent); 422 insufficient_stock (the
         *     warehouse holds fewer); 404 stock_not_found (the warehouse has none of a product at all).
         */
        post: operations["post_api_orders_partials_record"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every connection by name, with its health. */
        get: operations["get_api_shops_list"];
        put?: never;
        /**
         * ShopConnectionInput → 201 with `webhook_secret` (once) and `webhook_url`. 409 shop_url_taken, shop_name_taken;
         *     404 warehouse_not_found; 422 shop_url_invalid (not https, a private host; `detail.reason` says which).
         */
        post: operations["post_api_shops_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shops/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One connection. 404 shop_not_found. */
        get: operations["get_api_shops_show"];
        /**
         * ShopConnectionInput: blank consumer_key/consumer_secret keep the saved ones. 404 shop_not_found; the create's
         *     409 and 422.
         */
        put: operations["put_api_shops_update"];
        post?: never;
        /** 204; 409 shop_has_orders when orders came from it (deactivate it instead). Its inbox goes with it. */
        delete: operations["delete_api_shops_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shops/{id}/webhook-secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The webhook URL and signing secret to paste in WooCommerce (the consumer secret is never readable). */
        get: operations["get_api_shops_webhook_secret"];
        put?: never;
        /** Rotates the signing secret → the new one, to paste. Deliveries signed with the old one are refused from now. */
        post: operations["post_api_shops_webhook_secret_rotate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shops/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ShopTestInput (the URL and keys as typed, each blank one the saved one): "Test connection", 15 s, never an
         *     error status — `rest.ok` and `rest.error` say what happened. 404 shop_not_found.
         */
        post: operations["post_api_shops_test"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shops/{id}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A page of the connection's inbox, newest first (the list contract: `?status=failed` or filter[status][],
         *     filter[kind][], filter[reason_code][], filter[received_at][from|to], filter[remote_order_id], filter[customer];
         *     q over the shop order number and the customer).
         */
        get: operations["get_api_shops_deliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shops/{id}/deliveries/{deliveryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One inbox row with its body. 404 delivery_not_found (also another connection's). */
        get: operations["get_api_shops_delivery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shops/{id}/deliveries/{deliveryId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Runs the import again from the stored body: `placed` with its order, or still `failed` with the new reason. */
        post: operations["post_api_shops_delivery_retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shops/{id}/deliveries/{deliveryId}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Marks the row discarded (a placed row stays placed). */
        post: operations["post_api_shops_delivery_discard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shops/{id}/outbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The connection's writes in a status, newest first: `?status=` pending, sent or failed (the default: what the
         *     health counts). 404 shop_not_found; 422 for another status.
         */
        get: operations["get_api_shops_outbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shops/{id}/outbox/{outboxId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Queues a write again, due now → the row as it is afterwards (pending; sent or failed once the queue has run
         *     it). A row already sent is answered as it is. 404 shop_not_found / outbox_not_found (also another
         *     connection's row).
         */
        post: operations["post_api_shops_outbox_retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/quick-phrases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The active phrases in order. `?all=1`: every one, the hidden too (an admin's; anyone else still gets the active
         *     ones).
         */
        get: operations["get_api_quick_phrases"];
        put?: never;
        /** QuickPhraseInput: a phrase at the end → 201. */
        post: operations["post_api_quick_phrases_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/quick-phrases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** QuickPhraseInput: renames it or switches it off. 404 quick_phrase_not_found. */
        put: operations["put_api_quick_phrases_update"];
        post?: never;
        /** 204. 404 quick_phrase_not_found. */
        delete: operations["delete_api_quick_phrases_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The analytics IDs every signed-in page loads (null: that tool is off). Any signed-in user. */
        get: operations["get_api_settings_public"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Settings › Email: the SMTP server (never its password: `has_password`), the sender, the printer and the cc, each
         *     with where the effective value comes from (settings, env, none).
         */
        get: operations["get_api_settings_email"];
        /**
         * EmailSettingsInput: saves Settings › Email (a blank password keeps the saved one; everything empty clears it, the
         *     env applies) → EmailSettingsOutput; 422 on a bad address or a host that is not a host name alone. A blank
         *     password is kept only while the host stays the same.
         */
        put: operations["put_api_settings_email_save"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/email/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * TestEmailInput: sends "KF Inventory test email" to `to` through the effective server, at once (not queued) →
         *     202 with the host it went through; 502 smtp_failed with the server's message in detail.reason; 429
         *     test_email_too_soon more than once in 10 s; 422 on from_address when no sender is set anywhere.
         */
        post: operations["post_api_settings_email_test"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Settings › Analytics: the GA4 Measurement ID and the Clarity Project ID (null: that tool is off). */
        get: operations["get_api_settings_analytics"];
        /** AnalyticsSettingsInput: G-XXXXXXX and the Clarity Project ID (empty turns one off); 422 on a wrong shape. */
        put: operations["put_api_settings_analytics_save"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The legacy webhook URL's switch (on until turned off: Decisions 8) and the hits it took since it was turned off. */
        get: operations["get_api_settings_webhooks"];
        /** WebhookSettingsInput: turns the legacy webhook URL off (410 from then on; its counter starts at 0) or on. */
        put: operations["put_api_settings_webhooks_save"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A page of invoices, newest first: the list contract (q over code, customer name and email; filters code,
         *     customer, payment_method[], created_at, total, walk_in[] yes/no (yes: no customer); sorts code, customer,
         *     created_at, total; facets of payment_method and walk_in).
         */
        get: operations["get_api_invoices_list"];
        put?: never;
        /**
         * InvoiceInput: creates an invoice (the customer is `customer_id`, or found by id, email or phone and updated, or
         *     created from `customer`; with no address typed, the customer's first one is copied). 409 invoice_code_taken.
         */
        post: operations["post_api_invoices_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/next-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The code the next invoice is offered: the newest invoice's code plus one, or the year and 0001 for the first. */
        get: operations["get_api_invoices_next_code"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One invoice. 404 invoice_not_found. */
        get: operations["get_api_invoices_show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The invoice as a PDF. 404 invoice_not_found. */
        get: operations["get_api_invoices_pdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        QuickPhraseOutput: {
            id: number;
            text: string;
            position: number;
            active: boolean;
        };
        SessionOutput: {
            id: number;
            username: string;
            name?: string | null;
            email?: string | null;
            roles: string[];
        };
        UserOutput: {
            id: number;
            name: string;
            username: string;
            email?: string | null;
            /** The roles assigned (not the ones reached through the hierarchy) */
            roles: string[];
            enabled: boolean;
        };
        FacetCountOutput: {
            value: string;
            count: number;
        };
        ProductStockOutput: {
            warehouse_id: number;
            quantity: number;
            /** 1: in stock; 0: incoming */
            status: number;
        };
        ProductOutput: {
            id: number;
            uuid: string;
            code: string;
            title: string;
            detail?: string | null;
            /** 1: active; 0: inactive */
            status: number;
            /** Format: float */
            price?: number | null;
            stock: components["schemas"]["ProductStockOutput"][];
        };
        UploadResultOutput: {
            /** Rows stored (created or added to) */
            stored: number;
        };
        WarehouseRefOutput: {
            id: number;
            name: string;
        };
        StockOutput: {
            /** The stock row */
            id: number;
            /** 1: in stock; 0: incoming, waiting for approval */
            status: number;
            quantity: number;
            product_id: number;
            /** The product's */
            uuid: string;
            code: string;
            title: string;
            detail?: string | null;
            /** Format: float */
            price?: number | null;
            warehouse: components["schemas"]["WarehouseRefOutput"];
        };
        StockTotalsOutput: {
            /** The sum of the quantities */
            units: number;
            /**
             * The sum of quantity × price, in dollars
             * Format: float
             */
            value: number;
        };
        ApprovedOutput: {
            approved: number;
        };
        WarehouseOutput: {
            id: number;
            name: string;
            /** The X-WC-Webhook-Source values that send orders here */
            urls: string[];
        };
        CountryRefOutput: {
            id: number;
            name: string;
            code?: string | null;
        };
        StateRefOutput: {
            id: number;
            name: string;
            code?: string | null;
            country: components["schemas"]["CountryRefOutput"];
        };
        CityRefOutput: {
            id: number;
            name: string;
            state: components["schemas"]["StateRefOutput"];
        };
        AddressOutput: {
            id: number;
            address?: string | null;
            zip_code?: string | null;
            /** 1: billing; 2: shipping (as the WooCommerce webhook stores them) */
            address_type?: number | null;
            city?: components["schemas"]["CityRefOutput"] | null;
        };
        CustomerOutput: {
            id: number;
            first_name?: string | null;
            last_name?: string | null;
            email?: string | null;
            phone?: string | null;
            addresses: components["schemas"]["AddressOutput"][];
        };
        CityOutput: {
            id: number;
            name: string;
        };
        StateOutput: {
            id: number;
            name: string;
            code?: string | null;
            cities: components["schemas"]["CityOutput"][];
        };
        CountryOutput: {
            id: number;
            name: string;
            code?: string | null;
            states: components["schemas"]["StateOutput"][];
        };
        CommentAuthorOutput: {
            id: number;
            name: string;
        };
        ShopRefOutput: {
            id: number;
            name: string;
            /**
             * The connection is active and takes order notes: a comment can be sent to the shop.
             * @default false
             */
            takes_notes: boolean;
        };
        OrderCommentOutput: {
            id: number;
            content?: string | null;
            /** ISO 8601; a legacy comment without a date carries the order's, with `approximate` */
            created_at?: string | null;
            /** true when created_at is the order's date, not the comment's */
            approximate: boolean;
            /** null for a shop note, or a legacy comment without a user */
            author?: components["schemas"]["CommentAuthorOutput"] | null;
            /** app (typed here), shop (a note pulled from the shop), phrase (a quick phrase) */
            origin: string;
            /** the connection a shop note came from */
            shop?: components["schemas"]["ShopRefOutput"] | null;
            pinned: boolean;
            /** ISO 8601 */
            pinned_at?: string | null;
            pinned_by?: components["schemas"]["CommentAuthorOutput"] | null;
            /** the comment was also sent to the order's shop as an order note */
            sent_to_shop: boolean;
        };
        CustomerRefOutput: {
            id: number;
            first_name?: string | null;
            last_name?: string | null;
            email?: string | null;
            phone?: string | null;
        };
        PinnedCommentOutput: {
            id: number;
            content: string;
            /** ISO 8601; the order's date when the comment has none (legacy rows) */
            created_at?: string | null;
        };
        OrderOutput: {
            id: number;
            code?: string | null;
            /** 1 created, 2 processed, 3 completed, 4 partial, 5 sent, 6 delivered */
            status: number;
            /** 1 web (WooCommerce), 2 phone */
            source: number;
            /** 1 credit card, 2 PayPal */
            payment_method?: number | null;
            comment?: string | null;
            /** ISO 8601 */
            created_at?: string | null;
            warehouse?: components["schemas"]["WarehouseRefOutput"] | null;
            customer?: components["schemas"]["CustomerRefOutput"] | null;
            comments_count: number;
            /** The shop connection the order came from (shop_order_link); null for orders typed here or imported before connections */
            shop?: components["schemas"]["ShopRefOutput"] | null;
            pinned_comment?: components["schemas"]["PinnedCommentOutput"] | null;
        };
        OrderLineProductOutput: {
            code: string;
            title: string;
            detail?: string | null;
        };
        OrderLineOutput: {
            /** The product's */
            uuid: string;
            quantity: number;
            product: components["schemas"]["OrderLineProductOutput"];
        };
        OrderDetailOutput: {
            id: number;
            code?: string | null;
            status: number;
            source: number;
            payment_method?: number | null;
            comment?: string | null;
            /** ISO 8601 */
            created_at?: string | null;
            warehouse?: components["schemas"]["WarehouseRefOutput"] | null;
            customer?: components["schemas"]["CustomerOutput"] | null;
            comments: components["schemas"]["OrderCommentOutput"][];
            products: components["schemas"]["OrderLineOutput"][];
            /** The shop connection the order came from (shop_order_link); null for orders typed here or imported before connections */
            shop?: components["schemas"]["ShopRefOutput"] | null;
            pinned_comment?: components["schemas"]["PinnedCommentOutput"] | null;
        };
        ShopSyncConnectionOutput: {
            id: number;
            name: string;
            imported: number;
            skipped: number;
            /** Why the shop could not be read; null when it was */
            error?: string | null;
        };
        ShopsSyncResultOutput: {
            imported: number;
            skipped: number;
            /** Connections that could not be read */
            failed: number;
            connections: components["schemas"]["ShopSyncConnectionOutput"][];
        };
        PartialLineProductOutput: {
            code: string;
        };
        PartialLineOutput: {
            uuid: string;
            quantity: number;
            product: components["schemas"]["PartialLineProductOutput"];
        };
        PendingLineOutput: {
            uuid: string;
            quantity: number;
        };
        OrderPartialsOutput: {
            order_id: number;
            code?: string | null;
            status: number;
            products: components["schemas"]["OrderLineOutput"][];
            products_aggregate: components["schemas"]["PartialLineOutput"][];
            pending: components["schemas"]["PendingLineOutput"][];
            inventory: components["schemas"]["StockOutput"][];
        };
        ShopCapabilitiesOutput: {
            /** Processed → processing, Sent and Delivered → completed */
            order_status: boolean;
            /** Comments marked "also send to the shop" */
            order_note: boolean;
        };
        ShopHealthOutput: {
            last_webhook_at?: string | null;
            last_import_at?: string | null;
            last_pull_at?: string | null;
            last_pull_ok_at?: string | null;
            last_failure_at?: string | null;
            /** bad_signature, unknown_product, keys_read_only, unreachable… */
            last_failure_code?: string | null;
            last_failure?: string | null;
            /** Deliveries waiting in the inbox */
            failed_deliveries: number;
            /** Writes to the shop that failed every retry */
            failed_pushes: number;
        };
        ShopConnectionOutput: {
            id: number;
            name: string;
            site_url: string;
            active: boolean;
            warehouse: components["schemas"]["WarehouseRefOutput"];
            email_printer: boolean;
            capabilities: components["schemas"]["ShopCapabilitiesOutput"];
            /** The connection's own webhook URL, to paste in WooCommerce */
            webhook_url: string;
            has_keys: boolean;
            health: components["schemas"]["ShopHealthOutput"];
            /** Only in the answer that created the connection */
            webhook_secret?: string | null;
        };
        WebhookSecretOutput: {
            webhook_secret: string;
            webhook_url: string;
        };
        ShopRestTestOutput: {
            ok: boolean;
            store_name?: string | null;
            wc_version?: string | null;
            /** null: unknown until a write succeeded (a read cannot prove write access) */
            can_write?: boolean | null;
            /** The shop's message when it failed (never the keys) */
            error?: string | null;
        };
        ShopTestResultOutput: {
            rest: components["schemas"]["ShopRestTestOutput"];
            webhook_url?: string | null;
            webhook_secret_set: boolean;
        };
        OrderRefOutput: {
            id: number;
            code?: string | null;
        };
        DeliveryLineOutput: {
            sku?: string | null;
            quantity: number;
        };
        DeliverySummaryOutput: {
            customer?: string | null;
            lines: components["schemas"]["DeliveryLineOutput"][];
        };
        ShopDeliveryOutput: {
            id: number;
            /** webhook, pull or legacy */
            kind: string;
            remote_order_id?: string | null;
            /** placed, failed or discarded */
            status: string;
            /** bad_signature, unknown_product, no_warehouse, not_an_order, no_lines, duplicate, inactive */
            reason_code?: string | null;
            reason?: string | null;
            /** ISO 8601 */
            received_at: string;
            attempts: number;
            order?: components["schemas"]["OrderRefOutput"] | null;
            summary: components["schemas"]["DeliverySummaryOutput"];
        };
        ShopDeliveryDetailOutput: {
            id: number;
            /** webhook, pull or legacy */
            kind: string;
            remote_order_id?: string | null;
            /** placed, failed or discarded */
            status: string;
            reason_code?: string | null;
            reason?: string | null;
            /** ISO 8601 */
            received_at: string;
            attempts: number;
            order?: components["schemas"]["OrderRefOutput"] | null;
            summary: components["schemas"]["DeliverySummaryOutput"];
            /** The raw JSON body; null for a refused signature */
            payload?: string | null;
        };
        ShopOutboxOutput: {
            id: number;
            /** order_status or order_note */
            capability: string;
            order: components["schemas"]["OrderRefOutput"];
            payload: {
                [key: string]: unknown;
            };
            /** pending, sent or failed */
            status: string;
            attempts: number;
            last_error?: string | null;
            /** ISO 8601 */
            created_at: string;
        };
        PublicSettingsOutput: {
            ga4_measurement_id?: string | null;
            clarity_project_id?: string | null;
        };
        EmailSourcesOutput: {
            dsn: string;
            from: string;
            printer: string;
            cc: string;
        };
        EmailSettingsOutput: {
            dsn_host?: string | null;
            dsn_port?: number | null;
            dsn_user?: string | null;
            has_password: boolean;
            /** tls, ssl or none */
            encryption: string;
            from_address?: string | null;
            from_name?: string | null;
            printer_address?: string | null;
            cc: string[];
            source: components["schemas"]["EmailSourcesOutput"];
            env_host?: string | null;
        };
        TestEmailResultOutput: {
            queued: boolean;
            /** The SMTP host it went through */
            host?: string | null;
        };
        AnalyticsSettingsOutput: {
            /** G-XXXXXXX, from GA4 › Admin › Data streams */
            ga4_measurement_id?: string | null;
            /** Clarity › Settings › Project ID */
            clarity_project_id?: string | null;
        };
        WebhookSettingsOutput: {
            legacy_enabled: boolean;
            legacy_hits_since: number;
            /** ISO 8601 */
            legacy_last_hit_at?: string | null;
        };
        InvoiceProductOutput: {
            id: number;
            code: string;
        };
        InvoiceItemOutput: {
            id: number;
            description?: string | null;
            quantity: number;
            unit_price: string;
            discount?: string | null;
            total: string;
            product?: components["schemas"]["InvoiceProductOutput"] | null;
        };
        InvoiceOutput: {
            id: number;
            code?: string | null;
            status?: number | null;
            customer?: components["schemas"]["CustomerRefOutput"] | null;
            customer_nit?: string | null;
            customer_address?: string | null;
            comment?: string | null;
            payment_method?: string | null;
            items: components["schemas"]["InvoiceItemOutput"][];
            /** total minus tax_amount */
            subtotal?: string | null;
            tax_rate?: string | null;
            tax_amount?: string | null;
            total?: string | null;
            /** ISO 8601 */
            created_at?: string | null;
        };
        NextInvoiceCodeOutput: {
            code: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    put_api_quick_phrases_order: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuickPhraseOutput"][];
                };
            };
        };
    };
    post_api_auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOutput"];
                };
            };
        };
    };
    post_api_auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOutput"];
                };
            };
        };
    };
    get_api_users_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["UserOutput"][];
                        total: number;
                        page: number;
                        per_page: number;
                        facets?: {
                            [key: string]: components["schemas"]["FacetCountOutput"][];
                        };
                    };
                };
            };
        };
    };
    post_api_users_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOutput"];
                };
            };
        };
    };
    get_api_users_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOutput"];
                };
            };
        };
    };
    put_api_users_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOutput"];
                };
            };
        };
    };
    get_api_products_by_code: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOutput"];
                };
            };
        };
    };
    get_api_products_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOutput"];
                };
            };
        };
    };
    put_api_products_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOutput"];
                };
            };
        };
    };
    post_api_products_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOutput"];
                };
            };
        };
    };
    post_api_products_upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResultOutput"];
                };
            };
        };
    };
    get_api_products_template: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_stock_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["StockOutput"][];
                        total: number;
                        page: number;
                        per_page: number;
                        facets?: {
                            [key: string]: components["schemas"]["FacetCountOutput"][];
                        };
                        totals: components["schemas"]["StockTotalsOutput"];
                    };
                };
            };
        };
    };
    post_api_stock_move: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                from: string;
                to: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_api_stock_add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_api_stock_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_api_stock_approve_incoming: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovedOutput"];
                };
            };
        };
    };
    get_api_warehouses_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarehouseOutput"][];
                };
            };
        };
    };
    put_api_warehouses_rename: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarehouseOutput"];
                };
            };
        };
    };
    get_api_customers_page: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["CustomerOutput"][];
                        total: number;
                        page: number;
                        per_page: number;
                        facets?: {
                            [key: string]: components["schemas"]["FacetCountOutput"][];
                        };
                    };
                };
            };
        };
    };
    post_api_customers_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOutput"];
                };
            };
        };
    };
    get_api_customers_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOutput"][];
                };
            };
        };
    };
    get_api_customers_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOutput"];
                };
            };
        };
    };
    put_api_customers_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOutput"];
                };
            };
        };
    };
    delete_api_customers_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_locations_tree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryOutput"][];
                };
            };
        };
    };
    get_api_order_comments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        comments: components["schemas"]["OrderCommentOutput"][];
                    };
                };
            };
        };
    };
    put_api_orders_comments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        comments: components["schemas"]["OrderCommentOutput"][];
                    };
                };
            };
        };
    };
    post_api_order_comments_add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderCommentOutput"];
                };
            };
        };
    };
    post_api_order_comments_pin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderCommentOutput"];
                };
            };
        };
    };
    delete_api_order_comments_unpin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderCommentOutput"];
                };
            };
        };
    };
    get_api_orders_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["OrderOutput"][];
                        total: number;
                        page: number;
                        per_page: number;
                        facets?: {
                            [key: string]: components["schemas"]["FacetCountOutput"][];
                        };
                    };
                };
            };
        };
    };
    post_api_orders_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailOutput"];
                };
            };
        };
    };
    get_api_orders_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailOutput"];
                };
            };
        };
    };
    put_api_orders_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailOutput"];
                };
            };
        };
    };
    delete_api_orders_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_api_orders_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailOutput"];
                };
            };
        };
    };
    post_api_orders_sync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopsSyncResultOutput"];
                };
            };
        };
    };
    get_api_orders_pdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_orders_remaining_pdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_orders_xls: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_orders_partials: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPartialsOutput"];
                };
            };
        };
    };
    post_api_orders_partials_record: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPartialsOutput"];
                };
            };
        };
    };
    get_api_shops_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopConnectionOutput"][];
                };
            };
        };
    };
    post_api_shops_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopConnectionOutput"];
                };
            };
        };
    };
    get_api_shops_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopConnectionOutput"];
                };
            };
        };
    };
    put_api_shops_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopConnectionOutput"];
                };
            };
        };
    };
    delete_api_shops_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_shops_webhook_secret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookSecretOutput"];
                };
            };
        };
    };
    post_api_shops_webhook_secret_rotate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookSecretOutput"];
                };
            };
        };
    };
    post_api_shops_test: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopTestResultOutput"];
                };
            };
        };
    };
    get_api_shops_deliveries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ShopDeliveryOutput"][];
                        total: number;
                        page: number;
                        per_page: number;
                        facets?: {
                            [key: string]: components["schemas"]["FacetCountOutput"][];
                        };
                    };
                };
            };
        };
    };
    get_api_shops_delivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                deliveryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopDeliveryDetailOutput"];
                };
            };
        };
    };
    post_api_shops_delivery_retry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                deliveryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopDeliveryOutput"];
                };
            };
        };
    };
    post_api_shops_delivery_discard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                deliveryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopDeliveryOutput"];
                };
            };
        };
    };
    get_api_shops_outbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopOutboxOutput"][];
                };
            };
        };
    };
    post_api_shops_outbox_retry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                outboxId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopOutboxOutput"];
                };
            };
        };
    };
    get_api_quick_phrases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuickPhraseOutput"][];
                };
            };
        };
    };
    post_api_quick_phrases_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuickPhraseOutput"];
                };
            };
        };
    };
    put_api_quick_phrases_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuickPhraseOutput"];
                };
            };
        };
    };
    delete_api_quick_phrases_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_settings_public: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicSettingsOutput"];
                };
            };
        };
    };
    get_api_settings_email: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailSettingsOutput"];
                };
            };
        };
    };
    put_api_settings_email_save: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailSettingsOutput"];
                };
            };
        };
    };
    post_api_settings_email_test: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestEmailResultOutput"];
                };
            };
        };
    };
    get_api_settings_analytics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSettingsOutput"];
                };
            };
        };
    };
    put_api_settings_analytics_save: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSettingsOutput"];
                };
            };
        };
    };
    get_api_settings_webhooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookSettingsOutput"];
                };
            };
        };
    };
    put_api_settings_webhooks_save: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookSettingsOutput"];
                };
            };
        };
    };
    get_api_invoices_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["InvoiceOutput"][];
                        total: number;
                        page: number;
                        per_page: number;
                        facets?: {
                            [key: string]: components["schemas"]["FacetCountOutput"][];
                        };
                    };
                };
            };
        };
    };
    post_api_invoices_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceOutput"];
                };
            };
        };
    };
    get_api_invoices_next_code: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextInvoiceCodeOutput"];
                };
            };
        };
    };
    get_api_invoices_show: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceOutput"];
                };
            };
        };
    };
    get_api_invoices_pdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
