export {
  createShop,
  deleteShop,
  discardDelivery,
  getDelivery,
  getShop,
  getWebhookSecret,
  listDeliveries,
  listOutbox,
  listShops,
  retryDelivery,
  retryOutbox,
  rotateWebhookSecret,
  testShop,
  updateShop,
} from './api/shopConnectionApi';
export type {
  ShopCapabilities,
  ShopConnection,
  ShopConnectionPayload,
  ShopDelivery,
  ShopDeliveryDetail,
  ShopHealth,
  ShopOutboxEntry,
  ShopsSyncResult,
  ShopTestPayload,
  ShopTestResult,
  WebhookSecret,
} from './api/shopConnectionApi';
